# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_axf_mainshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_mainshow',
            name='longname1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='axf_mainshow',
            name='longname2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='axf_mainshow',
            name='longname3',
            field=models.CharField(max_length=100),
        ),
    ]
