# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_axf_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_shopcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsNumber', models.IntegerField(default=1)),
                ('isSelecy', models.BooleanField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.axf_goods')),
            ],
            options={
                'db_table': 'axf_shopcar',
            },
        ),
        migrations.CreateModel(
            name='axf_user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('user_pass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_user_info',
            },
        ),
        migrations.AddField(
            model_name='axf_shopcar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.axf_user_info'),
        ),
    ]
