# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-12 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_auto_20180810_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='axf_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('orderNumber', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.axf_user_info')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='axf_order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsNumber', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.axf_goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='axf.axf_order')),
            ],
            options={
                'db_table': 'axf_order_info',
            },
        ),
        migrations.AlterField(
            model_name='axf_shopcar',
            name='isSelecy',
            field=models.BooleanField(default=False),
        ),
    ]
