# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_auto_20180812_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='axf_order_info',
            name='goodsmoney',
            field=models.FloatField(default=1),
        ),
    ]
